# Generated by Django 3.1.6 on 2021-02-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPeriod',
            fields=[
                ('period', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('cron_string', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.IntegerField(blank=True, choices=[(1, 'Short'), (2, 'Medium'), (3, 'Long')], default=1, null=True)),
                ('status', models.CharField(choices=[('ideation', 'Ideation'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('recurring', 'Recurring')], default='ideation', max_length=16)),
                ('recurring_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.taskperiod')),
            ],
        ),
    ]
