# Generated by Django 3.1.6 on 2021-05-09 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ideation', 'Ideation'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('past_due', 'Past Due')], default='ideation', max_length=16)),
                ('recurring_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadence.cadence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
