# Generated by Django 3.1.6 on 2021-02-18 07:44

from django.db import migrations
from task_management.utils import TaskPeriodTypes

def add_task_periods(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TaskPeriod = apps.get_model('task_management', 'TaskPeriod')

    for period, cron_string in zip(TaskPeriodTypes.names, TaskPeriodTypes.values):
        task_period = TaskPeriod(period = period, cron_string = cron_string)
        task_period.save()

class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_task_periods),
    ]
