# Generated by Django 3.1.6 on 2021-02-18 07:44

from django.db import migrations

def add_task_periods(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TaskPeriod = apps.get_model('task_management', 'TaskPeriod')
    task_period_strings = [
        "daily|Every day|0 8 * * *",
        "weekly|Every week|0 0 * * 0",
        "monthly|Every month|0 0 1 * *",
        "quarter|Every quarter|0 0 1 */3 *",
        "yearly|Every year|0 0 1 1 *",
    ]
    for task_period_string in task_period_strings:
        period, note, cron_string = task_period_string.split('|')
        task_period = TaskPeriod(period = period, note = note, cron_string = cron_string)
        task_period.save()

class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_task_periods),
    ]
