# Generated by Django 3.1.6 on 2021-02-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=16, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('cron_string', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='notes',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.taskperiod'),
        ),
    ]
