# Generated by Django 3.1.6 on 2021-02-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20210218_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurring_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_management.taskperiod'),
        ),
    ]
