# Generated by Django 3.1.6 on 2021-02-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_auto_20210221_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskperiod',
            name='note',
        ),
    ]
