# Generated by Django 3.1.6 on 2021-02-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_remove_taskperiod_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('recurring', 'Recurring'), ('past_due', 'Past Due')], default='ideation', max_length=16),
        ),
    ]
