# Generated by Django 3.1.6 on 2021-03-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_auto_20210227_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='term',
        )
    ]
