# Generated by Django 3.1.6 on 2021-03-07 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_auto_20210306_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked'), ('past_due', 'Past Due')], default='ideation', max_length=16),
        ),
    ]
