# Generated by Django 3.1.6 on 2021-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('period', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cron_string', models.CharField(max_length=32)),
            ],
        ),
    ]
