# Generated by Django 3.1.6 on 2021-05-09 03:42
# https://docs.djangoproject.com/en/3.2/topics/migrations/#data-migrations
from django.db import migrations

# https://crontab.guru/
initial_cadences = {
    "daily": '0 8 * * *',
    "weekly": '0 0 * * 0',
    "monthly": '0 0 1 * *',
    "quarterly": '0 0 1 */3 *',
    "yearly": '0 0 1 1 *',
    "monday": '0 0 * * MON',
    "tuesday": '0 0 * * TUE',
    "wednesday": '0 0 * * WED',
    "thursday": '0 0 * * THU',
    "friday": '0 0 * * FRI',
    "saturday": '0 0 * * SAT',
    "sunday": '0 0 * * SUN',
}

def add_cadences(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Cadence = apps.get_model('cadence', 'Cadence')

    for cadence, cron_string in initial_cadences.items():
        cadence = Cadence(period = cadence, cron_string = cron_string)
        cadence.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cadence', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_cadences),
    ]
