# Generated by Django 3.1.6 on 2021-05-09 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('preferred_cadence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadence.cadence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_management.recurringcontact')),
                ('prev_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_management.contactinteraction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
