# Generated by Django 3.1.6 on 2021-03-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0004_default_foreignkey_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinteraction',
            name='prev_interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_management.contactinteraction'),
        ),
    ]
